language: android
jdk: oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
  - android-sdk-preview-license-c81a61d9
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - linters/install-linters.sh
  - ci/install-protoc.sh
script:
  - gradle reactive-blerpc:assemble
  - ci/generate-reactive-plugin.sh
  - reactive-blerpc/tests/test.sh
  - gradle reactive-blerpc-test:assemble reactive-blerpc-test:testReleaseUnitTest
  - gradle blerpcproto:assemble
  - gradle assembleRelease --stacktrace --no-daemon
  - gradle testReleaseUnitTest --info
  - linters/run-linters.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST_BRANCH" == "" ]; then
          gradle bintrayUpload -PbintrayUser=monnoroch -PbintrayKey="$BINTRAY_API_KEY" -PdryRun=false;
    fi
notifications:
  email: false
